sudo: required

language: android

jdk: oraclejdk8

env:
  global:
    - ANROID_API_LEVEL = "26"
    - ANDROID_BUILD_TOOLS_VERSION = "26.0.2"

android :
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android - $ANDROID_API_LEVEL
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-$ANDROID_API_LEVEL
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

script :
  - bash ./build.sh 792666621:AAElCDptqnb9ViQdCxSyFn6gPAN-nXGkuOc -1001228305673 dev gradle=v3

before_install:
  - yes | sdkmanager "platforms;android-28"
  - chmod +x gradlew